### ISSUE TITLE
"this node is not a swarm manager" error while trying docker-compose

### ISSUE THREAD

**Issue by LucaMoiana** [warnyul/traefik-docker-compose#1]
Hi, I ended up on this repo looking for an easy way to reverse-proxy using traefik in my test machine.
I did follow the instructions and change .env.dev using my variables, but when I do 

> ./scripts/start.sh

I get 

> this node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again

Since I'm not running a swarm mode nor I want, is there any way you can help me running this on a simple docker machine?
thanks

**Comment by warnyul** [comment]
Hi, I have updated the compose file, start and deploy scripts. If you set `SWARM_MODE=false` in .env file, the script will use `docker-compose up` instead of `docker stack deploy`, so you do not need run `docker swarm init` or `docker swarm join` before start this service.

**Comment by LucaMoiana** [comment]
thank you, I can run start script now and access traefik dasboard, on an unsercure connection, but when I try to reach my domain I get 

> "http: TLS handshake error from 93.144.197.176:60398: remote error: tls: unknown certificate"

**Comment by warnyul** [comment]
I have used the `start.sh` only for local development, so it do not use `docker-compose.acme.yml`, but you can add with `-f`  like this `docker-compose up -f docker-compose.yml -f docker-compose.acme.yml`. If you will use `docker-compose.yml`, I recommend to check the acme config. Because it is configured for a Digital Ocean droplet.
